version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  reviewers:
  - sluongng
  assignees:
  - sluongng
  ignore:
  - dependency-name: org.jetbrains.kotlin:kotlin-maven-allopen
    versions:
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: io.github.microutils:kotlin-logging
    versions:
    - 1.12.0
    - 2.0.5
  - dependency-name: com.google.cloud.tools:jib-maven-plugin
    versions:
    - 2.7.1
    - 2.8.0
  - dependency-name: org.junit.jupiter:junit-jupiter
    versions:
    - 5.7.0
