language: java
sudo: false

jdk:
  - openjdk11

cache:
  directories:
    - "$HOME/.m2/repository"

script:
  - cat ${HOME}/.m2/settings.xml
  - ./mvnw verify

after_success:
  - bash <(curl -s https://codecov.io/bash)
